"""Make BVN and NIN required

Revision ID: 34d1d744ec44
Revises: 405b35015cf4
Create Date: 2026-07-01 17:48:28.117878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d1d744ec44'
down_revision: Union[str, None] = '405b35015cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('informal_worker', 'bvn',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('informal_worker', 'nin',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('informal_worker', 'nin',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('informal_worker', 'bvn',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###
