"""Add Admin Models

Revision ID: 405b35015cf4
Revises: 873a5a8e8c6b
Create Date: 2026-07-01 15:15:46.827617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '405b35015cf4'
down_revision: Union[str, None] = '873a5a8e8c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ajo_collector', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.add_column('ajo_collector', sa.Column('failed_pin_attempts', sa.Integer(), nullable=True))
    op.add_column('ajo_collector', sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consent_log', sa.Column('event_type', sa.String(length=100), nullable=True))
    op.add_column('consent_log', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('consent_log', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_log', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('consent_log', 'details')
    op.drop_column('consent_log', 'event_type')
    op.drop_column('ajo_collector', 'lockout_until')
    op.drop_column('ajo_collector', 'failed_pin_attempts')
    op.drop_column('ajo_collector', 'pin_hash')
    # ### end Alembic commands ###
