"""add password_hash to worker

Revision ID: 9de59a7ee833
Revises: 34d1d744ec44
Create Date: 2026-07-03 11:17:28.593325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de59a7ee833'
down_revision: Union[str, None] = '34d1d744ec44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informal_worker', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informal_worker', 'password_hash')
    # ### end Alembic commands ###
